# sample regex patterns
ignore:
  - "*.pb.go"
  - "main.go"
  - "**/e2e/**"
  - "mocks/**"
  - "examples/**"

coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 5%
