package main

import (
	"context"
	"encoding/csv"
	"encoding/json"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strconv"
	"testing"
	"time"

	"github.com/rxtech-lab/argo-trading/e2e/backtest/wasm/testhelper"
	"github.com/rxtech-lab/argo-trading/internal/backtest/engine"
	"github.com/rxtech-lab/argo-trading/internal/runtime/wasm"
	"github.com/rxtech-lab/argo-trading/internal/types"
	"github.com/stretchr/testify/suite"
)

const wasmPath = "./rsi_comparison_plugin.wasm"

// engineConfigYAML configures the backtest engine to match the
// `backtesting.py` reference run: 10,000 USD initial capital, zero
// commission, FIFO PnL accounting, decimal precision 0 (integer shares).
const engineConfigYAML = `
initial_capital: 10000
broker: zero_commission
portfolio_calculation: fifo
decimal_precision: 0
`

// floatTolerance is the absolute tolerance for comparing prices and PnL
// values across the two engines. Floating-point arithmetic and CSV
// round-tripping introduce noise on the order of 1e-9, so 1e-6 is more
// than safe while still catching real semantic divergence.
const floatTolerance = 1e-6

// RSIComparisonTestSuite verifies that argo's backtest engine running the
// RSI(14) WASM strategy produces the exact same trades, orders and PnL as
// the reference results generated by `backtesting.py` in
// `internal/indicator/test_data/src/comparison`.
//
// The reference dataset (`comparison_data.parquet`) and reference outputs
// (`results/*`) are committed to the repository so this test is fully
// hermetic: regenerating them requires explicitly running the Python
// pipeline.
type RSIComparisonTestSuite struct {
	testhelper.E2ETestSuite
}

func TestRSIComparisonTestSuite(t *testing.T) {
	suite.Run(t, new(RSIComparisonTestSuite))
}

// SetupTest initialises the backtest engine with the comparison-aligned
// config. We deliberately do NOT call `testhelper.RunWasmStrategyTest`
// downstream because that helper re-initialises the engine with an empty
// config, which would discard our broker / portfolio_calculation /
// initial_capital settings.
func (s *RSIComparisonTestSuite) SetupTest() {
	s.E2ETestSuite.SetupTest(engineConfigYAML)
}

// pythonTrade represents a row of the committed `results/trades.csv`.
type pythonTrade struct {
	ExecutedAt    time.Time
	Side          string
	Quantity      float64
	Price         float64
	PnL           float64
	CumulativePnL float64
	Symbol        string
}

// pythonSummary represents the committed `results/summary.json`.
type pythonSummary struct {
	Symbol             string  `json:"symbol"`
	NumTrades          int     `json:"num_trades"`
	NumBuys            int     `json:"num_buys"`
	NumSells           int     `json:"num_sells"`
	NumClosedPositions int     `json:"num_closed_positions"`
	RealizedPnL        float64 `json:"realized_pnl"`
	FinalEquity        float64 `json:"final_equity"`
	InitialCash        float64 `json:"initial_cash"`
}

// testDataDir resolves the absolute path of the comparison dataset folder
// relative to this test file, independently of the test's working directory.
// The path is cleaned to ensure it is a canonical absolute reference even
// though both inputs are derived from compile-time `runtime.Caller`.
func testDataDir() string {
	_, thisFile, _, _ := runtime.Caller(0)
	return filepath.Clean(filepath.Join(filepath.Dir(thisFile), "..", "..", "..", "..", "internal", "indicator", "test_data"))
}

func (s *RSIComparisonTestSuite) TestArgoMatchesBacktestingPy() {
	dataDir := testDataDir()
	parquetPath := filepath.Join(dataDir, "comparison_data.parquet")
	resultsDir := filepath.Join(dataDir, "results")

	// Ensure the committed reference fixtures exist before we even try to run
	// argo, so a missing fixture fails with a clear message instead of a
	// downstream comparison error.
	_, err := os.Stat(parquetPath)
	s.Require().NoError(err, "required fixture comparison_data.parquet is missing; regenerate with `python -m comparison.main`")
	for _, name := range []string{"trades.csv", "orders.csv", "summary.json"} {
		_, err := os.Stat(filepath.Join(resultsDir, name))
		s.Require().NoErrorf(err, "required reference file results/%s is missing; regenerate with `python -m comparison.main`", name)
	}

	tmpFolder := s.runArgoBacktest(parquetPath)

	argoTrades, err := testhelper.ReadTrades(&s.E2ETestSuite, tmpFolder)
	s.Require().NoError(err)
	argoOrders, err := testhelper.ReadOrders(&s.E2ETestSuite, tmpFolder)
	s.Require().NoError(err)

	pyTrades := s.loadPythonTrades(filepath.Join(resultsDir, "trades.csv"))
	pySummary := s.loadPythonSummary(filepath.Join(resultsDir, "summary.json"))

	// Sort argo trades by execution time to align with the Python ordering.
	sort.SliceStable(argoTrades, func(i, j int) bool {
		return argoTrades[i].ExecutedAt.Before(argoTrades[j].ExecutedAt)
	})

	// Drop unfilled / failed orders so the order-count assertion is comparing
	// like for like with the Python reference (which only contains executed
	// orders).
	filledOrders := make([]types.Order, 0, len(argoOrders))
	for _, o := range argoOrders {
		if o.Status == types.OrderStatusFilled || o.IsCompleted {
			filledOrders = append(filledOrders, o)
		}
	}

	// 1. Counts.
	s.Require().Equal(pySummary.NumTrades, len(argoTrades),
		"argo trade count must match backtesting.py")
	s.Require().Equal(pySummary.NumBuys+pySummary.NumSells, len(filledOrders),
		"argo filled order count must match backtesting.py")
	s.Require().Equal(len(pyTrades), len(argoTrades),
		"trades.csv row count and argo trade count must match")

	// 2. Per-trade equality of side, quantity, price, executed_at, PnL.
	for i, py := range pyTrades {
		argo := argoTrades[i]
		s.Require().Equal(py.Symbol, argo.Order.Symbol, "trade %d: symbol mismatch", i)
		s.Require().Equal(py.Side, argoSideString(argo.Order.Side),
			"trade %d: side mismatch", i)
		s.Require().True(py.ExecutedAt.Equal(argo.ExecutedAt.UTC()),
			"trade %d: executed_at mismatch (python=%s argo=%s)",
			i, py.ExecutedAt, argo.ExecutedAt.UTC())
		s.Require().InDelta(py.Quantity, argo.ExecutedQty, floatTolerance,
			"trade %d: quantity mismatch", i)
		s.Require().InDelta(py.Price, argo.ExecutedPrice, floatTolerance,
			"trade %d: price mismatch", i)
		s.Require().InDelta(py.PnL, argo.PnL, floatTolerance,
			"trade %d: per-trade PnL mismatch", i)
	}

	// 3. Cumulative realized PnL.
	var argoRealized float64
	for _, t := range argoTrades {
		argoRealized += t.PnL
	}
	s.Require().InDelta(pySummary.RealizedPnL, argoRealized, floatTolerance,
		"realized PnL mismatch (python=%v argo=%v)", pySummary.RealizedPnL, argoRealized)

	if len(argoTrades) > 0 {
		s.Require().InDelta(argoRealized, argoTrades[len(argoTrades)-1].CumulativePnL, floatTolerance,
			"argo cumulative PnL on the last trade should equal the realized total")
		s.Require().InDelta(pyTrades[len(pyTrades)-1].CumulativePnL, argoTrades[len(argoTrades)-1].CumulativePnL, floatTolerance,
			"final cumulative PnL must match between engines")
	}

	s.T().Logf("compared %d trades; realized PnL = %.6f", len(argoTrades), argoRealized)
}

// runArgoBacktest loads the WASM strategy into the already-initialised
// engine from SetupTest, runs it against the committed parquet, and returns
// the temp folder containing all output artefacts.
func (s *RSIComparisonTestSuite) runArgoBacktest(parquetPath string) string {
	t := s.T()

	tmpFolder := t.TempDir()
	resultPath := filepath.Join(tmpFolder, "results")
	cfgPath := filepath.Join(tmpFolder, "config.json")

	cfgBytes, err := json.Marshal(struct{}{})
	s.Require().NoError(err)
	s.Require().NoError(os.WriteFile(cfgPath, cfgBytes, 0o600))

	rt, err := wasm.NewStrategyWasmRuntime(wasmPath)
	s.Require().NoError(err)
	_, err = rt.GetConfigSchema()
	s.Require().NoError(err)

	s.Require().NoError(s.Backtest.SetDataPath(parquetPath))
	s.Require().NoError(s.Backtest.LoadStrategy(rt))
	s.Require().NoError(s.Backtest.SetResultsFolder(resultPath))
	s.Require().NoError(s.Backtest.SetConfigPath(cfgPath))

	s.Require().NoError(s.Backtest.Run(context.Background(), engine.LifecycleCallbacks{}))

	return tmpFolder
}

// argoSideString maps argo's PurchaseType enum to the BUY/SELL strings used
// in the Python CSV.
func argoSideString(side types.PurchaseType) string {
	switch side {
	case types.PurchaseTypeBuy:
		return "BUY"
	case types.PurchaseTypeSell:
		return "SELL"
	}
	return string(side)
}

func (s *RSIComparisonTestSuite) loadPythonTrades(path string) []pythonTrade {
	f, err := os.Open(path) //nolint:gosec // path is constructed from test source dir
	s.Require().NoError(err)
	defer f.Close()

	r := csv.NewReader(f)
	rows, err := r.ReadAll()
	s.Require().NoError(err)
	s.Require().GreaterOrEqual(len(rows), 1, "trades.csv must have a header row")

	header := rows[0]
	col := func(name string) int {
		for i, h := range header {
			if h == name {
				return i
			}
		}
		s.T().Fatalf("trades.csv missing required column %q", name)

		return -1
	}
	idxTime := col("executed_at")
	idxSide := col("side")
	idxQty := col("quantity")
	idxPrice := col("price")
	idxPnL := col("pnl")
	idxCum := col("cumulative_pnl")
	idxSym := col("symbol")

	trades := make([]pythonTrade, 0, len(rows)-1)
	for i, row := range rows[1:] {
		ts, err := time.Parse(time.RFC3339, normalizeRFC3339(row[idxTime]))
		s.Require().NoErrorf(err, "row %d: bad timestamp %q", i, row[idxTime])
		qty, err := strconv.ParseFloat(row[idxQty], 64)
		s.Require().NoError(err)
		price, err := strconv.ParseFloat(row[idxPrice], 64)
		s.Require().NoError(err)
		pnl, err := strconv.ParseFloat(row[idxPnL], 64)
		s.Require().NoError(err)
		cum, err := strconv.ParseFloat(row[idxCum], 64)
		s.Require().NoError(err)
		trades = append(trades, pythonTrade{
			ExecutedAt:    ts.UTC(),
			Side:          row[idxSide],
			Quantity:      qty,
			Price:         price,
			PnL:           pnl,
			CumulativePnL: cum,
			Symbol:        row[idxSym],
		})
	}

	return trades
}

// normalizeRFC3339 ensures naive ISO timestamps emitted by the Python runner
// (e.g. "2024-01-01T10:20:00") are accepted by `time.Parse(time.RFC3339, ...)`
// by appending a UTC zone designator when none is present.
func normalizeRFC3339(s string) string {
	if len(s) >= 1 && s[len(s)-1] == 'Z' {
		return s
	}

	if len(s) >= 6 {
		c := s[len(s)-6]
		if c == '+' || c == '-' {
			return s
		}
	}

	return s + "Z"
}

func (s *RSIComparisonTestSuite) loadPythonSummary(path string) pythonSummary {
	data, err := os.ReadFile(path) //nolint:gosec // path is constructed from test source dir
	s.Require().NoError(err)
	var summary pythonSummary
	s.Require().NoError(json.Unmarshal(data, &summary))

	return summary
}
